"""
Generate Enriched Bilingual Descriptions - Using Task Tool

This script generates actual AI descriptions using Claude Code's Task tool
to validate the pre-enrichment pipeline improvements.
"""

import json
import subprocess
import sys

# First, run the TypeScript enrichment to get enriched prompts
print("🔄 Running enrichment pipeline to get enriched prompts...")
print()

result = subprocess.run(
    ["bun", "run", "scripts/test-enrichment-pipeline.ts"],
    capture_output=True,
    text=True,
    cwd="/Users/chrism/Project with Claude/AgentAthens/agent-athens"
)

if result.returncode != 0:
    print("❌ Enrichment failed:")
    print(result.stderr)
    sys.exit(1)

print("✅ Enrichment complete!")
print()
print("="*80)
print("📝 ENRICHED PROMPTS READY")
print("="*80)
print()
print("The enriched prompts have been generated by the pipeline.")
print("These prompts contain ~280 words of context (vs. 15 words without enrichment).")
print()
print("Next: Use Task tool to generate 6 descriptions (3 events × 2 languages)")
print("Expected: ~5 minutes total (30-45s per description)")
print()
print("Each description will be generated with:")
print("  - Venue context (100-150 words)")
print("  - Genre keywords (15-20 terms)")
print("  - Event type context (40-50 words)")
print("  - Artist info (when available)")
print()
print("Target: 4/6 descriptions pass (415-425 words)")
print()
